version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: student_task_db
      MYSQL_ROOT_PASSWORD: 2004
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=student_task_db
      - DB_USER=root
      - DB_PASSWORD=2004
      - DB_PORT=3306
    depends_on:
      - db

  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
