# Generated by Django 6.0.4 on 2026-05-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_task', '0002_profile_delete_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='rubric_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Graded', 'Graded'), ('Returned', 'Returned')], default='Submitted', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='tags',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
