# Generated by Django 6.0.4 on 2026-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_task', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
