# Generated by Django 6.0.4 on 2026-05-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_task', '0006_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio_avatars/'),
        ),
    ]
